### ISSUE TITLE
Throws Error with Electron 1.6.1

### ISSUE THREAD

**Issue by biomade** [simonhochrein/electromon#2]
I am running Electron 1.6.1 and when I run electromon ./app.js I get the following error:
`   
Error: Command failed: pwd
'pwd' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:464:13)
    at Object.execSync (child_process.js:504:13)
    at Object.<anonymous> (C:\Users\xxxx\AppData\Roaming\npm\node_modules\electromon\index.js:30:47)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3`

**Comment by simonhochrein** [comment]
Electromon doesn't use the latest version of electron,
I haven't had much time to work on these projects,
any pull requests would be helpful.

**Comment by biomade** [comment]
thanks for the update. I will move on then

**Comment by simonhochrein** [comment]
Sorry i couldn't help :-(
